// Fontawesomme
import { library } from '@fortawesome/fontawesome-svg-core'

import {
    faCheckSquare,
    faDraftingCompass,
    faArrowRight,
    faUser,
    faCog,
    faQuestionCircle,
    faThLarge,
    faUsers,
    faChild,
    faComment,
    faSearch,
    faBell,
    faChevronDown,
    faChevronUp,
    faBars,
    faHome,
    faSignOutAlt,
    faPlus,
    faMinus,
    faCommentAlt,
    faShareAlt,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faCheckSquare,
    faDraftingCompass,
    faArrowRight,
    faUser,
    faCog,
    faQuestionCircle,
    faThLarge,
    faUsers,
    faChild,
    faComment,
    faSearch,
    faBell,
    faChevronDown,
    faChevronUp,
    faBars,
    faHome,
    faSignOutAlt,
    faPlus,
    faMinus,
    faCommentAlt,
    faShareAlt,
);